# Generated by Django 4.0.2 on 2022-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('image', models.URLField()),
                ('saves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
