# Generated by Django 4.0.2 on 2022-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_researchpapers_users_alter_conference_image_workexp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='day',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='users',
            name='contactno',
            field=models.IntegerField(null=True),
        ),
    ]
