# Generated by Django 4.0.2 on 2022-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_users_country_alter_users_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpapers',
            name='collab_ids',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
